#!/bin/bash

set -e

if [ "$#" -ne 1 ] || [ "$1" == "-h" ]; then
    echo 'Usage: `change-base-url <domain>`.';
    echo 'Example: `change-base-url https://my-custom-url.test/`';
    echo 'Please make sure to include the training slash.';
    exit;
fi

URL=$1
php bin/magento config:set web/unsecure/base_url $URL &
php bin/magento config:set web/secure/base_url $URL &
php bin/magento config:set web/unsecure/base_link_url $URL &
php bin/magento config:set web/secure/base_link_url $URL &

wait

bin/magento cache:flush config
