#!/bin/bash

set -e

echo "Enabling flat catalog"
php bin/magento config:set catalog/frontend/flat_catalog_category 1
php bin/magento config:set catalog/frontend/flat_catalog_product 1
php bin/magento cache:flush
